name: C/C++ CI

on: 
  push:
  workflow_dispatch:

jobs:
  windows_cmake_vs:
    runs-on: windows-latest
    env:
      CMAKE_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\
    strategy:
      matrix:
        configuration:
          - Debug
          - RelWithDebInfo
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install ninja
      run: pip install ninja

    - name: Create Solution Files
      shell: cmd
      run: '"%CMAKE_PATH%\cmake.exe" -B build -DSENTRY_BACKEND=crashpad'

    - name: Build solution files
      run: '"%CMAKE_PATH%\cmake.exe" --build build --parallel --clean-first --config ${{ matrix.configuration }}'

    - name: Copy files to a single folder
      run: '"%CMAKE_PATH%\cmake.exe" --install build --prefix install/${{ matrix.configuration }} --config ${{ matrix.configuration }}'

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        # Artifact name
        name: ${{ matrix.configuration }}
        # A file, directory or wildcard pattern that describes what to upload
        path: install/${{ matrix.configuration }}

  pack_nuget:
    runs-on: windows-latest
    needs: [windows_cmake_vs]
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v2
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.6

      - run: |
          cp ./Debug/include/sentry.h package/include
          cp ./Debug/bin/* package/native/debug/dll
          cp ./Debug/lib/sentry.lib package/native/debug/lib
          cp ./RelWithDebInfo/bin/* package/native/release/dll
          cp ./RelWithDebInfo/lib/sentry.lib package/native/release/lib

      - name: Pack nuget package
        run: |
          nuget pack package

      - name: Push package to artifact store in Azure
        run: |
          nuget sources Add -Source https://pkgs.dev.azure.com/oasys-software/_packaging/oasys-software-libraries/nuget/v3/index.json -Name "oasys-software-libraries" -UserName "unused" -Password "${{ secrets.WRITE_PACKAGES_PAT }}" -StorePasswordInClearText
          nuget push -Source "oasys-software-libraries" -ApiKey az *.nupkg

  upload_binaries_to_sentry:
    runs-on: ubuntu-latest
    needs: [windows_cmake_vs]
    strategy:
      matrix:
        project:
          - gsa
          - adsec
          - frew
          - pdisp
          - xdisp
          - alp
          - pile
          - slope
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.6

      - name: Install Sentry
        run: |
          curl -sL https://sentry.io/get-cli/ | bash

      - name: Upload to Sentry
        run: |
          sentry-cli --auth-token ${{ secrets.SENTRY_TOKEN }} upload-dif -o arup-digital -p ${{ matrix.project }} ./Debug/bin/ --log-level=info
          sentry-cli --auth-token ${{ secrets.SENTRY_TOKEN }} upload-dif -o arup-digital -p ${{ matrix.project }} ./RelWithDebInfo/bin/ --log-level=info
